In [142]:
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.metrics.pairwise import cosine_similarity as cs

In [ ]:
df = pd.read_csv("data/preproccess_data.csv")
df.head(10)

,Unnamed: 0,imdb_id,title,tags
0,0,111161,theshawshankredemption,theshawshankredemption drama 1994 0111161
1,1,468569,thedarkknight,thedarkknight action crime drama 2008 0468569
2,2,1375666,inception,inception action adventure scifi 2010 1375666
3,3,137523,fightclub,fightclub crime drama thriller 1999 0137523
4,4,816692,interstellar,interstellar adventure drama scifi 2014 0816692
5,5,109830,forrestgump,forrestgump drama romance 1994 0109830
6,6,110912,pulpfiction,pulpfiction crime drama 1994 0110912
7,7,133093,thematrix,thematrix action scifi 1999 0133093
8,8,120737,thelordoftherings:thefellowshipofthering,thelordoftherings:thefellowshipofthering adven...
9,9,167260,thelordoftherings:thereturnoftheking,thelordoftherings:thereturnoftheking adventure...

In [144]:
df = df[['imdb_id', 'title', 'tags']]
df.head(10)

,imdb_id,title,tags
0,111161,theshawshankredemption,theshawshankredemption drama 1994 0111161
1,468569,thedarkknight,thedarkknight action crime drama 2008 0468569
2,1375666,inception,inception action adventure scifi 2010 1375666
3,137523,fightclub,fightclub crime drama thriller 1999 0137523
4,816692,interstellar,interstellar adventure drama scifi 2014 0816692
5,109830,forrestgump,forrestgump drama romance 1994 0109830
6,110912,pulpfiction,pulpfiction crime drama 1994 0110912
7,133093,thematrix,thematrix action scifi 1999 0133093
8,120737,thelordoftherings:thefellowshipofthering,thelordoftherings:thefellowshipofthering adven...
9,167260,thelordoftherings:thereturnoftheking,thelordoftherings:thereturnoftheking adventure...

In [145]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [146]:
vector = cv.fit_transform(df['tags']).toarray()

In [147]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(16252, 5000))

In [148]:
cv.get_feature_names_out()

array(['000km', '000movie', '000timesgoodnight', ..., 'zootopia',
       'zootopia2', 'çalgiçengi'], shape=(5000,), dtype=object)

In [149]:
import nltk

In [150]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [151]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [152]:
df['tags'] = df['tags'].apply(stem)

In [153]:
similarity = cs(vector)

In [ ]:
df2 = pd.read_csv("data/cleaned-movie-data.csv")

In [155]:
def recommend(movie_name):
    movie_index = df[df['title'] == movie_name].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

    movie_dict = {}
    for i in movies_list:
        movie_dict[i[0]] = (df2.iloc[i[0]].title)   
    print(movie_dict)    
    return